### ISSUE TITLE
add default wrapper for BigDecimal

### ISSUE THREAD

**Issue by ritonglue** [bpoole6/CSV-Parser#10]
The type BigDecimal is missing in DefaultReadWrappers and DefaultWriteWrappers

**Comment by bpoole6** [comment]
A default wrapper for BigDecimal was explicitly left out because its not a primitive data type.

**Comment by ritonglue** [comment]
I recommand to add it. It's in the standard (and I use them to import money values).
In JSF, there is a default converter for BigDecimal : `jakarta.faces.convert.BigDecimalConverter` so why not in CSV ?
