### ISSUE TITLE
File encoding has not been set

### ISSUE THREAD

**Issue by ritonglue** [bpoole6/CSV-Parser#5]
File encoding must be set

`[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!`

`[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!`

**Comment by bpoole6** [comment]
What code are you referencing?

**Comment by ritonglue** [comment]
It's from maven. I guess you have to set the project.build.sourceEncoding property.
