### ISSUE TITLE
Don't use Class.newInstance

### ISSUE THREAD

**Issue by ritonglue** [bpoole6/CSV-Parser#8]
clazz.newInstance() should be replaced by
 clazz.getDeclaredConstructor().newInstance()

Class.newInstance is deprecated since java 9.

**Comment by bpoole6** [comment]
The compilation target is 1.8 not java 11. If the library were to be updated it would work in a runtime environment of 1.8. 

An error such as this will occur
`java: cannot access com.quirk.csv.processor.CSVProcessor
  bad class file: /C:/Users/bpool/.m2/repository/io/github/bpoole6/quirk-csv/1.0.2-SNAPSHOT/quirk-csv-1.0.2-SNAPSHOT.jar!/com/quirk/csv/processor/CSVProcessor.class
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.`

**Comment by ritonglue** [comment]
My pull request didn't change the compilation target. It can stay in 1.8. It's just about replacing the call to Class.newInstance() which has the problems explained later in the documentation >= java 9.
